### ISSUE TITLE
Struct fields are readonly

### ISSUE THREAD

**Issue by mpartel** [Deukhoofd/csharp_binder#1]
When csharp_binder generates structs, it marks all fields as `readonly`, but it doesn't generate a constructor.
As far as I can tell, such a struct cannot be initialized in C# (to anything other than all zeroes).

**Comment by Deukhoofd** [comment]
The concept for the readonly structs was for C# to be able to read the objects Rust passes back, but you're right that we should be able to instantiate a struct in C# for Rust to read. I'll see about generating constructors.

**Comment by mpartel** [comment]
Thanks!

**Comment by mpartel** [comment]
The change in 0.2.1 [doesn't seem to work](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyAMABMugHQBKArgHbBgC2ApiQJI0MBOA9gA4DKHANzABjBgGcA3DhwBtXsHYVhwADIBDAJ6cKwABTqtOgNJgqMEvwCOFBjTBroBAMIALNe37ACAXmduPDMAkAKpUIpwwDACUALo4yADMBGIKSl4AogAeanTcEAw4AN44BKVESQBmEJxqXgAaBIUEAOaBEgSmYMDtAL4lZYkEVTVeAJpS2P2lg1k5eQy6UYV9k9hl5QSzufm6w7UEmVBD1fsaUVONF+sNvpkT6+ujPgQa92UrPUA==)

**Comment by mpartel** [comment]
I don't think the explicit parameterless constructor is necessary. [This works.](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyAMABMugHQBKArgHbBgC2ApiQJI0MBOA9gA4DKHANzABjBgGcA3DhwBtXsHYVhwADIBDAJ6cKwABTqtOgNJgqMEvwCOFBjTBroBAMIALNe37ACAXmduPDMAkAKpUIpwwDACUALo4yADMBGIKSl4AogAeanTcEAw4AN44BKVESQBmEJxqXgAaBIUEAOaBEgSmYMDtAL4lZYkEVTVeAJpS2P2lg1k5eQy6w7UEmVBD1csaUVONO2UEDb6ZE/v7oz4EGidlfdi38UlozrvY+4PIACwEALJqprpRF6nMpUBgAdwIs1y+UaBwu6DW518qAIPWuwNBEKh810CIIqCi6NROFuQA=)

**Comment by Deukhoofd** [comment]
You're absolutely correct, forgot for a moment there that C# doesn't allow you to do so. Thanks for the heads up! Should be fixed in 0.2.2.
